bash RunTableSimulation.sh convex 0
bash RunTableSimulation.sh convex 0.25
bash RunTableSimulation.sh convex 0.5
bash RunTableSimulation.sh convex 0.75
bash RunTableSimulation.sh convex 1.0
bash RunTableSimulation.sh nonconvex 0
bash RunTableSimulation.sh nonconvex 0.25
bash RunTableSimulation.sh nonconvex 0.5
bash RunTableSimulation.sh nonconvex 0.75
bash RunTableSimulation.sh nonconvex 1.0
