all: poiseuille_convex poiseuille_nonconvex

poiseuille_convex: poiseuille_convex.cpp
	g++ poiseuille_convex.cpp -o poiseuille_convex

poiseuille_nonconvex: poiseuille_nonconvex.cpp
	g++ poiseuille_nonconvex.cpp -o poiseuille_nonconvex
